### ISSUE TITLE
Expose a "Service" that provides DiscoveryEndpoint information?

### ISSUE THREAD

**Issue by wallymathieugarantibil** [IdentityServer/IdentityServer4#840] opened 2017-02-23 15:59 UTC
- [X] I read and understood how to enable [logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)

Hi! This is not an issue, rather an enhancement to the identity server. In order to be able to do intelligent things in the code that uses IdentityServer4 we would like to access the discovery information.

Specifically, we would like trusted services to be able to communicate with the identity server by authenticating with bearer token auth. In order to get that to work we currently do the following:

https://github.com/IdentityServer/IdentityServer4.Samples/compare/dev...wallymathieu:dev

Also, we have to do a bit of song and dance in order to test things related to these API's on the server. It would be significantly easier (less hackish) if there was a DiscoveryService that DiscoveryEndpoint uses to generate the document.

**Comment by leastprivilege** [comment] 2017-02-27 16:02
I don't follow. explain please.

**Comment by wallymathieugarantibil** [comment] 2017-02-28 09:55
In order to be able to expose an API that uses identity server to authenticate users of the API, we use 
```
app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
```
However, when we need to test the code, that becomes a bit of a hassle, since the authority is a localhost:someport url, i.e. depends on network to get authority information.

In the tests I have written the following:
```
        protected override void UseJwtBearerAuth(IApplicationBuilder app)
        {
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap
                    = new Dictionary<string, string>();
            var cert = new SigningCredentials(new X509SecurityKey(Certificate), "RS256");
            var tokenValidationParameters = new TokenValidationParameters
            {
                IssuerSigningKeys = new[] { cert.Key },
                // The signing key must match!
                // Validate the JWT Issuer (iss) claim
                ValidateIssuer = true,
                ValidIssuer = IdentityOptions.Authority,

                // Validate the JWT Audience (aud) claim
                ValidateAudience = false,
                //ValidAudience = "ExampleAudience",

                // Validate the token expiry
                ValidateLifetime = true,

                // If you want to allow a certain amount of clock drift, set that here:
                ClockSkew = TimeSpan.Zero
            };
            var jwtBearerOptions = new JwtBearerOptions()
            {
                Authority = IdentityOptions.Authority,
                Audience = "someaudience",
                RequireHttpsMetadata = false,

                AutomaticAuthenticate = true,
                AutomaticChallenge = true,

                TokenValidationParameters = tokenValidationParameters,
                AuthenticationScheme = "Bearer",
            };

            jwtBearerOptions.ConfigurationManager = app.ApplicationServices.GetRequiredService<StaticOpenIdConnectConfigurationManager>();

            app.UseJwtBearerAuthentication(jwtBearerOptions);
        }


        private class StaticOpenIdConnectConfigurationManager : IConfigurationManager<OpenIdConnectConfiguration>
        {
            private readonly DiscoveryEndpoint _endpoint;
            private OpenIdConnectConfiguration _maybeConfiguration;
            private readonly IServiceProvider _requestServices;

            public StaticOpenIdConnectConfigurationManager(DiscoveryEndpoint endpoint, IServiceProvider requestServices)
            {
                _endpoint = endpoint;
                _maybeConfiguration = null;
                _requestServices = requestServices;
            }


            public async Task<OpenIdConnectConfiguration> GetConfigurationAsync(CancellationToken cancel)
            {
                if (_maybeConfiguration != null) return _maybeConfiguration;
                _maybeConfiguration = await GetConfiguration();
                return _maybeConfiguration;
            }

            private async Task<OpenIdConnectConfiguration> GetConfiguration()
            {
                var httpContext = new DefaultHttpContext();
                httpContext.Request.Method = "GET";
                httpContext.Request.Path = "/";
                httpContext.RequestServices = _requestServices;
                var res = await _endpoint.ProcessAsync(httpContext);
                var d = res as DiscoveryDocumentResult;
                if (d != null)
                {
                    return OpenIdConnectConfiguration.Create(Newtonsoft.Json.JsonConvert.SerializeObject(d.Document));
                }
                else
                {
                    throw new Exception($"Wrong type {res.GetType()} of response");
                }
            }

            public void RequestRefresh()
            {

            }
        }
```
In order to be able to test that the setup is correct. I don't like the fact that I have to fake a http context in order to be able to access the open id configuration.

**Comment by TomCJones** [comment] 2017-02-28 16:20
there is a bug in the openIdConnect certification code. The way that openIdConnect was designed does not account for the discrepancy between the schemes acct: and mailto: that do not employ port numbers and http: and https: on the other that do. I have written in special code to handle the test, much the same way that Volkswagen handled emission tests.  ..tom

________________________________

**Comment by leastprivilege** [comment] 2017-02-28 21:31
I still don't understand your real problem. Do you?

**Comment by wallymathieugarantibil** [comment] 2017-03-01 07:08
I want to be able to host API-s on the same site as I have IdentityServer4 hosted on...

**Comment by leastprivilege** [comment] 2017-03-01 07:20
To get rid of the network dependency you can use the back channel handler. Or don't use the middleware at all. During testing you don't care about token validation - only about the principal that is set in the pipeline.

**Comment by wallymathieugarantibil** [comment] 2017-03-01 07:47
The reason why I do want to test it is due to the fragility of the interaction of Mvc, middleware and IdentityServer. We had some issues related to that code configuration that I want to avoid.

**Comment by leastprivilege** [comment] 2017-03-01 08:11
So you will have a network dependency in any case.

Sorry maybe I am thick - but I don't understand your problem.

**Comment by wallymathieugarantibil** [comment] 2017-03-01 11:20
The question is mostly, would it be possible to add a method to DiscoveryEndpoint or a new class that returns the object instead of having to create a fake http context

**Comment by leastprivilege** [comment] 2017-03-01 12:03
and how do you want to call that?

Is IS in the same host as your test?

**Comment by wallymathieugarantibil** [comment] 2017-03-01 12:04
I want to call that from the Startup.cs of the IS instance in order to configure Jwt auth for internal API-s

**Comment by leastprivilege** [comment] 2017-03-01 12:15
And you are using the real web host for that? Or the test server?

**Comment by wallymathieugarantibil** [comment] 2017-03-01 12:16
We are using a real web host for it. When testing we want to make sure that everything is configured correctly - that's why we test against the IS Host.

**Comment by leastprivilege** [comment] 2017-03-01 12:18
Also - the discovery code must run in the context of an http request because we need to "calculate" certain things wrt to URLs. So I guess I cannot add the feature you are asking for.

**Comment by leastprivilege** [comment] 2017-03-01 12:19
So when you are using the real web host - what's the issue then to configure the real authority to fetch the disco information?

**Comment by wallymathieugarantibil** [comment] 2017-03-01 12:20
I worry that it's does not behave the same as the code I've tested.

**Comment by wallymathieugarantibil** [comment] 2017-03-01 12:21
Would it be OK if I send you a pull request with a suggestion ?

**Comment by leastprivilege** [comment] 2017-03-01 14:45
you can start by describing the changes you have in mind.

**Comment by leastprivilege** [comment] 2017-03-06 14:54
Closing this issue. Feel free to open a feature request with description.

**Closed by leastprivilege** 2017-03-06 14:54 UTC
Labels: question

**Comment by wallymathieugarantibil** [comment] 2017-03-07 15:58
Will do!

**Comment by leastprivilege** [comment] 2017-03-07 16:00
Might be obsolete - check the latest commit.

**Comment by wallymathieugarantibil** [comment] 2017-03-07 16:01
I do hope so!

**Comment by wallymathieugarantibil** [comment] 2017-03-09 12:12
Looks like there is a IDiscoveryResponseGenerator 👍
