### ISSUE TITLE
UserProfileService<ApplicationUser> does not add requested Api/scope claims to access token

### ISSUE THREAD

**Issue by Ruard** [IdentityServer/IdentityServer4#3042] opened 2019-02-17 10:23 UTC
The issue is in IdentityServer4.AspNetIdentity.

### Issue / Steps to reproduce the problem

```
services
    .AddIdentityServer()
    .AddAspNetIdentity<ApplicationUser>()
```

After some debugging I've noticed that when I use `AddAspNetIdentity`, the `DefaultProfileService` is replaced with `IdentityServer4.AspNetIdentity.ProfileService<ApplicationUser>`.

This should not be a problem, except that this implementation ignores the configured api/scope claims.

From `DefaultProfileService`:
```
public async Task GetProfileDataAsync(ProfileDataRequestContext context)
{
    context.AddRequestedClaims(context.Subject.Claims);
}
```

From `ProfileService<ApplicationUser>`, I've removed checks and logging:
```
public virtual async Task GetProfileDataAsync(ProfileDataRequestContext context)
{
    var sub = context.Subject?.GetSubjectId();
    var user = await UserManager.FindByIdAsync(sub);
    var principal = await ClaimsFactory.CreateAsync(user);
    context.AddRequestedClaims(principal.Claims);
}
```

Clearly `context.Subject.Claims` is not the same source as `principal.Claims`.

I wonder if it is necessary to replace `DefaultProfileService` with `ProfileService<ApplicationUser>`. Because I'm 'fixing' this by 'restoring' the `DefaultProfileService`:

```
services
    .AddIdentityServer()
    .AddAspNetIdentity<ApplicationUser>()
    .AddProfileService<DefaultProfileService>()
```

And in case I have a new field that needs be added as claim, I need to add my own custom profileservice anyways. Seems to me that `ProfileService<ApplicationUser>` could be removed.

---

In the situation I've tested I have an ExtensionGrant where a claim is added:

```
public class AuthorizationGrantValidator : IExtensionGrantValidator
{
    public async Task ValidateAsync(ExtensionGrantValidationContext context)
    {
        // Simplified sample
        var sub = context.Request.Raw.Get("sub");
        var claims = new List<Claim> { new Claim("requested_scope", "api1") };
        context.Result = new GrantValidationResult(sub, GrantType, claims);
    }
}
```

Where `requested_scope` is configured in ApiClaims. With `DefaultProfileService` the claim makes it to the access token, but not with `ProfileService<ApplicationUser>`.

**Comment by brockallen** [comment] 2019-04-10 16:58
> Clearly context.Subject.Claims is not the same source as principal.Claims.

The issue is that normally you'd not issue all the claims into the session at IdentityServer (and thus there normally would be no claims of value in `context.Subject.Claims`. Thus, if you're using ASP.NET Identity, our default profile implementation uses the standard ASP.NET Identity architecture to create claims for a user in ASP.NET Identity, which is the user claims principal factory. 

So in short, the design if that if you are using ASP.NET Identity, make your user claims principal factory return claims that you'd want to make available in your tokens.

**Comment by brockallen** [comment] 2019-04-11 13:25
Closing. If you still have issues, feel free to reopen.

**Closed by brockallen** 2019-04-11 13:25 UTC
Labels: question
