### ISSUE TITLE
Identity Server 4 Redirect Fails In Edge and IE 11

### ISSUE THREAD

**Issue by dresdor** [IdentityServer/IdentityServer4#3101] opened 2019-03-14 20:41 UTC
I'm experiencing a very weird issue in our redirects with Microsoft's browsers.

We have two web applications secured behind an identity server 4 implementation.  One of these applications (Sales App) is an angular 5 app with a very basic MVC application serving it up, and the other (Admin App) is a fully fledged MVC application.  

When we try to load SalesAppUrl it redirects to our identity portal, as I'd expect, and allows us to login.  After the redirect, though, Edge and IE both give the error INET_E_DOWNLOAD_FAILURE, and look like they did not even try to load the page (from network traffic).   The redirect from the identity server occur, but all other calls stay stuck at "pending" with a 0s time.  The only console information is navigation occured and "CSS3121: The media query -ms-viewport has been deprecated."

The real weird thing is that when we try to go to AdminAppUrl, it does the same thing for Edge, but actually loads fully in IE 11 without issue.

When I run the SalesApp locally, connected to the same identity server as the live version, everything works fine.

Our middleware configuration is in [this SO question](https://stackoverflow.com/questions/55170698/identity-server-4-authorized-app-not-working-in-ie-11-or-edge)

I am working at creating a minimally functional version of this to show the issue (though it's a challenge due to the fact that local code works fine).

Versions:
Microsoft Edge 41.16299.967.0
Microsoft EdgeHTML 16.16299
Internet Explorer 11.0.110
IdentityServer4.AspNetIdentity (2.3.0)
IdentityServer4.Entity.Framework(2.3.2)
.Net Core 2.1

**Comment by brockallen** [comment] 2019-04-10 18:45
Sorry no idea. Any update?

**Comment by dresdor** [comment] 2019-04-11 13:24
Unfortunately other priorities have taken precedence over this issue.  I
will be looking at it hopefully soon.

-Marshall

**Comment by brockallen** [comment] 2019-04-11 13:32
I'll close this for now then until you have an update.

**Comment by BertCotton** [comment] 2019-12-10 21:29
We are able able to reproduce this bug.  We are using IdentityServer4.  
When using Chrome or FF we are able to authenticate.  When using IE 11 or Edge we do not get redirected.

The network traffic goes to /callback/authorize/callback?...
to <identityserver>/Account/ExternalLogin but that post only stays Pending.

Would it be best to reopen this bug or to submit a new bug?

**Comment by brockallen** [comment] 2019-12-11 02:54
We can reopen. Can you provide repo steps?

**Comment by BertCotton** [comment] 2019-12-11 03:31
Sure thing.
We have IdentityServer4 setup with federated login to O365
We have a local web app that requests the user be logged in. This web app is using DotNet Core 2.1 with the extension method "services.AddOpenIdconnect()"

When I go to our web app in IE 11 or Chrome my network traffic looks like this:
![2019-12-10 20_20_12-Window](https://user-images.githubusercontent.com/6656765/70588739-f64e8800-1b8a-11ea-8a70-68a970f62247.png)

It is odd that we see 7 requests and they are all pending.

Doing the same test (going to the web page) in Chrome or FF does not have this effect.  A single request to the /connect/authorize is returned as a 302, and we proceed to /Login then to O365 /authorize and then to /Account/ExternalLoginCallback in IdentityServer.

**Comment by egissan** [comment] 2020-01-13 11:13
Hi,

We had the same issue - a combination of nginx/Edge/HTTP2 (https://github.com/kubernetes/ingress-nginx/issues/3499). Hope this helps.

Cheers

**Comment by DaleyKD** [comment] 2020-01-17 15:43
We're having the same issue.  Also running this in a kube pod with nginx.  Works fine in Chrome/FF, but not IE/Edge.

Using IdentityServer4 to connect to Azure AD.  I get thru the login.microsoft.com page, but on redirect back, no joy.

Also, /.well-known/openid-configuration isn't working.

**Comment by DaleyKD** [comment] 2020-01-17 15:59
Additional info: If Fiddler is open, it works.  I guess that's because Fiddler is acting as a proxy?

**Comment by egissan** [comment] 2020-01-19 10:30
"Fiddler doesn't support HTTP2 yet so, the connection changes to HTTP 1.1". 

The solution is in the link I've posted. Basically you need to set http2-max-field-size: "16k" in nginx settings.

**Comment by Gutek** [comment] 2020-02-03 14:27
I have the opposite issue... in chrome, it does not work but edge (latest one) works perfectly.

in chrome, I'm going into login page infinite loop.

Google Chrome is up to date
Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by DaleyKD** [comment] 2020-02-03 14:48
@egissan : Was finally able to test out what you suggested.  Bumping http2-max-field-size and http2-max-header-size to 64k fixed two issues for us!

**Comment by krisztiankocsis** [comment] 2020-03-09 14:25
We had the same problem with Angular + .NET Core 3 with SignalR, Nginx in front via HTTP/2. Increasing these two limits solved the problem. Note that the reaching of limit is clearly stated in Nginx log files if you enable the debug log.

**Comment by brockallen** [comment] 2020-09-07 15:16
Given the future of IE/Edge, I think we can close this.

**Closed by brockallen** 2020-09-07 15:16 UTC
Labels: investigating, question
