### ISSUE TITLE
Impossible install IdentityServer4 from Nuget

### ISSUE THREAD

**Issue by jsantanainel** [IdentityServer/IdentityServer4#858] opened 2017-03-01 09:08 UTC
Could not retrieve information about "IdentityServer4" from remote source "https://s3-eu-west-1.amazonaws.com/serverlinux/FindPackagesById()?id='IdentityServer4 '"

All IdentityServer's packages are unavailable.

Thanks.

**Comment by naeemsarfraz** [comment] 2017-03-01 09:39
@jsantanainel I just created a new project (ASP.NET Core) and installed the IdentityServer4 package so it seems to be working for me.

There was an S3 outage last night so I'm not sure if that is affecting things for you. But from what I understand that affected the us-east-1 region.

**Comment by jsantanainel** [comment] 2017-03-01 09:53
@naeemsarfraz It should be because of the interrupt you mention since I can install other packages without problems. I'll wait a few hours to see if it works out. Thank you very much.

**Comment by leastprivilege** [comment] 2017-03-01 11:39
closing

**Closed by leastprivilege** 2017-03-01 11:39 UTC

**Comment by jsantanainel** [comment] 2017-03-01 20:28
Imposible install IdentityServer´s packages from Ireland.

**Comment by brockallen** [comment] 2017-03-01 22:32
> Impossible install IdentityServer´s packages from Ireland.

Not sure what the issue is: https://twitter.com/venky_venky76v/status/837067301623107584

**Comment by leastprivilege** [comment] 2017-03-02 04:56
Several cloud providers had issues in the last days. 

If the problem persists, please contact nuget.org directly.
