### ISSUE TITLE
Token audience validation with SSL termination

### ISSUE THREAD

**Issue by bendetat** [IdentityServer/IdentityServer4#784] opened 2017-02-06 04:56 UTC
- [-] I read and understood how to enable [logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)

### Issue / Steps to reproduce the problem
We are using SSL termination, so while the public URI for the auth server is `https://auth.example.com`, the IdentityServer4 instance is listening at `http://auth.example.com:8101`, with an AWS ELB (enterprise load balancer) sitting in between and providing SSL termination. There are multiple services on the same machine using SSL termination, hence the non-default port number.

When validating a token from a second, internal system (using `http://auth.example.com:8101/connect/introspect`) the token validation fails:

```
fail: IdentityServer4.Validation.TokenValidator[0]
      JWT token validation error: Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audien
ce validation failed. Audiences: 'http://auth.example.com/resources, my-api'. Did not match: validationParamete
rs.ValidAudience: 'http://auth.example.com:8101/resources' or validationParameters.ValidAudiences: 'null'.
         at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityTo
ken, TokenValidationParameters validationParameters)
         at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenVali
dationParameters validationParameters)
         at IdentityServer4.Validation.TokenValidator.<ValidateJwtAsync>d__11.MoveNext()
```

Note that the token audiences uses `http://` not `https://`, I'm not sure where the generated token gets that URI from as it's not configured anywhere and I'm requesting it via `https://auth.example.com/connect/token` so it's not coming from the request AFAIK. I just made sure I used `http://...` in my workaround.

The root cause seems to be that `TokenValidator.ValidateAccessTokenAsync()` uses the local host URI from `HttpContext` as the basis for the `ValidAudience` passed in to the token handler. I've worked around this by copying the `TokenValidator` class into my project and changing https://github.com/IdentityServer/IdentityServer4/blob/afb09a6872e12a2c77dcc7854841453e2f5f52fb/src/IdentityServer4/Validation/TokenValidator.cs#L200 from:

```
ValidAudience = audience
```

to something similar to:

```
ValidAudiences = new [] {
    audience,
    "http://api.example.com/resources"
}
```

and then adding the custom token validator to the services just prior to adding IdentityServer:

```
services.AddTransient<ITokenValidator, MyTokenValidator>();
services.AddIdentityServer ....
```

I also had to provide the same URIs sans `/resources` in the `ValidIssuers` collection to solve the next, related issue. Is this the correct solution? It seems that somehow being able to provide additional public URIs to the framework's `TokenValidator` would be better.

### Relevant parts of the log file

Per above.

**Comment by leastprivilege** [comment] 2017-02-06 08:52
So the issue is, that IS thinks it runs on http - that's because of the load balancing setup (It actually does run on http - but this is not how clients talk to it).

There is a MW from MS that uses the typical override headers emitted by reverse proxies to adjust things like host name and protocol. Forgot the name - but that's what you need to put in place.

**Comment by bendetat** [comment] 2017-02-06 12:08
That pretty much sums up the situation.

Are you talking about the IIS URL Rewrite module (https://www.iis.net/downloads/microsoft/url-rewrite)?  I've had to use that before in a different 3rd party system that generated resource URLs based on the HTTP context. I'm self-hosting kestrel in this case, so I'm not sure if that will work but I'll give it a try. Being able to configure IdentityServer to work in this scenario without having to resort to URL Rewrite would be good though. I'll give it a try tomorrow, thanks.

**Comment by leastprivilege** [comment] 2017-02-06 13:16
There is asp.net core middleware (the headers middleware IIRC) that does the "re-writing" locally in the app.

**Comment by leastprivilege** [comment] 2017-02-22 15:27
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Closed by leastprivilege** 2017-02-22 15:27 UTC
Labels: question

**Comment by bendetat** [comment] 2017-02-22 22:26
We haven't had a chance to implement the middleware yet, my messy workaround above is still in place and working... The middleware sounds like a better solution though, when we can revisit this I'll update. Happy for this to stay closed. Thanks for your help.
