### ISSUE TITLE
Basic client authentication is broken if client secret contains + sign 

### ISSUE THREAD

**Issue by pritamsso** [IdentityServer/IdentityServer4#5254] opened 2021-05-12 21:43 UTC
Basic Client authentication is broken if the Client secret contains the `+` sign.

Notice the red underlined `+` sign which gets replaced with `space` 
![Screen Shot 2021-05-12 at 2 39 16 PM](https://user-images.githubusercontent.com/33366717/118047785-237b0900-b330-11eb-9f39-6f9c621f95ca.png)

This is happening due to the decode function [here](https://github.com/IdentityServer/IdentityServer4/blob/4c998dea822779d6a288fe56d81bb85fddcf9cc0/src/IdentityServer4/src/Validation/Default/BasicAuthenticationSecretParser.cs#L143) --> https://github.com/IdentityServer/IdentityServer4/blob/4c998dea822779d6a288fe56d81bb85fddcf9cc0/src/IdentityServer4/src/Validation/Default/BasicAuthenticationSecretParser.cs#L143

**Comment by brockallen** [comment] 2021-05-12 22:08
The client pwd/secret are encoded differently in OAuth:

https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1

**Comment by pritamsso** [comment] 2021-05-12 22:26
@brockallen - the issue is with the hardcoded `+` sign in decode function, which is in turn gets replaced with white space in client secret.

**Comment by leastprivilege** [comment] 2021-05-18 15:27
This was added for a reason. But I can't remember.

I will look into it ASAP.

**Comment by leastprivilege** [comment] 2021-05-19 07:11
I cannot reproduce the problem - maybe your input encoding is incorrect. Check the above link to the spec.

I added some tests to verify.

https://github.com/DuendeSoftware/IdentityServer/blob/1c3f1fadb0fa7a4bea3f4a6f7028cbfcff3b9918/test/IdentityServer.UnitTests/Validation/Secrets/BasicAuthenticationCredentialParsing.cs#L61-L85

**Comment by brockallen** [comment] 2021-05-19 13:54
Did your original client secret have a space or a + (plus sign) in it? Also, what library are you using client side to encode the client id and secret.

**Comment by brockallen** [comment] 2021-05-19 14:02
I think the short of it is that encoding a space to "+" is an old way of doing it and is no longer spec compliant. The extra call to `Replace("+", "%20")` is attempting to accommodate older libraries that do this. But strictly speaking a "+" should not be in a URL encoded value, as both space and "+" get encoded (to "%20" and "%2B" respectively).

**Comment by pritamsso** [comment] 2021-05-19 15:05
@brockallen - Yes we have a `+` sign in the Client Secret, and we are not using any library. Its our internal tool which is trying to obtain token using `password` grant and we are sending the client id and client secret as described here in basic authentiation section - https://identityserver4.readthedocs.io/en/latest/topics/client_authentication.html#authentication-using-a-shared-secret

Currently we are running on .net core 5 & Identity Server 4.1.1

**Comment by leastprivilege** [comment] 2021-05-19 15:28
These docs are outdated unfortunately.

Use this
https://github.com/DuendeSoftware/IdentityServer/blob/1c3f1fadb0fa7a4bea3f4a6f7028cbfcff3b9918/test/IdentityServer.UnitTests/Validation/Secrets/BasicAuthenticationCredentialParsing.cs#L75-L77

**Comment by pritamsso** [comment] 2021-05-19 15:50
Can we consider to remove the `+` sign hardcoding

**Comment by leastprivilege** [comment] 2021-05-19 16:19
> Can we consider to remove the + sign hardcoding

No. please update your encoding logic instead.

**Comment by pritamsso** [comment] 2021-05-19 17:42
I understand your perspective, but do we really need to URI encode the secrets which are not really part of uri and being passed in as headers value header.

**Comment by brockallen** [comment] 2021-05-19 17:54
If you look at any URL encoder and try to encode the string "a b+c" you get "a%20b%2Bc". The point is that a plaintext secret with a space or a plus should not carry over into the encoded value. Thus the recommendation that the encoding be fixed on the client side.

Try this one, for example: https://www.urlencoder.org/

**Comment by leastprivilege** [comment] 2021-05-19 19:48
> do we really need to URI encode the secrets

We need to encode them as specified in the RFC.

**Closed** 2021-06-09 01:26 UTC
Labels: wontfix
