### ISSUE TITLE
Allow soft delete for refresh tokens

### ISSUE THREAD

**Issue by MCFHTAGENTS** [IdentityServer/IdentityServer4#3061] opened 2019-02-26 11:40 UTC
I see the following in my log files:
```
2019-02-26 11:07:25.817 +00:00 [WRN] Invalid refresh token
2019-02-26 11:07:25.818 +00:00 [WRN] Refresh token validation failed. aborting., request details: []
```

It would be helpful if you told me which user's token was invalid so I can get them to trigger a refresh.

Thanks
Mark

**Comment by brockallen** [comment] 2019-02-26 12:43
> It would be helpful if you told me which user's token was invalid so I can get them to trigger a refresh.

If it's invalid, then we don't know which user it was for.

**Comment by MCFHTAGENTS** [comment] 2019-02-26 12:49
Hmm - am trying to ascertain what the use case is here then and how I get to an invalid refresh token. 

They are only ever tokens issued by IdentityServer4.

I can see how they might have expired, and even if they have expired and the refresh cycle hasn't worked (e.g. my website was down)  how they could be deemed invalid but they shouldn't have any other faults.

Everything is being persisted to databases (i.e. not in memory) 

Thanks
Mark

**Comment by MCFHTAGENTS** [comment] 2019-03-13 07:32
Hi there,
I have been further researching this and think I have figured out what is going on. My server was configured with EnableTokenCleanup set to true (as house keeping is a good thing right?!)
The code of that routine is here: `https://github.com/IdentityServer/IdentityServer4.EntityFramework.Storage/blob/0a4b800a88c5c3175f39ccac8514583522c9fb0f/src/TokenCleanup/TokenCleanup.cs`
The deletion rule is a straightforward token expiry time rule. In the real world this is too much brute force and we really need a rule that either includes a retention period (e.g. delete tokens that expired n days ago) or better still add a superseded flag to the token so that when it is refreshed and a replacement one is issued.
This way, when a client presents an expired token you will still have it and know what to do with it...

I hope that makes sense.
Regards
Mark

**Comment by jasonycw** [comment] 2019-03-19 02:35
We are encountering a similar errors in our identity server log.
We use SeriLog and there are quit a lot of 
```
{
    "Timestamp": "2019-03-19T01:48:36.1994739+00:00",
    "Level": "Warning",
    "MessageTemplate": "Refresh token validation failed. aborting., request details: {details}",
    "Properties": {
        "details": [],
        "RequestPath": "/connect/token",
        "Url": "http://identity.corp-prd.vpc/connect/token",
        "QueryString": "",
        "Method": "POST",
        ...
    }
}
```

It would be great if the log can include some more detail for better trouble shooting.
Maybe logging the `Invalid refresh token` isn't a huge security concern?

**Comment by brockallen** [comment] 2019-03-23 16:29
We can have a look // @leastprivilege

**Comment by jklawrence** [comment] 2019-03-27 18:45
We've just noticed empty request details in our logs too (on 2.3.0):
`{ "level": "ERROR", "logger": "IdentityServer4.Validation.TokenRequestValidator[0]", "message": "Transformed code verifier does not match code challenge, request details: []", "details": [] }`

I'll try to dig into it a little more when I have time.

**Comment by MCFHTAGENTS** [comment] 2019-03-27 18:52
@jklawrence - that doesn’t look related to the invalid refresh token issue here - can I suggest you do a new post?

**Comment by jklawrence** [comment] 2019-03-28 19:57
The empty request details all seem to be related in 2.3.0. The issue is with the log message templates.

`LogError`: https://github.com/IdentityServer/IdentityServer4/blob/2.3.0/src/Validation/Default/TokenRequestValidator.cs#L756
`LogWarning`: https://github.com/IdentityServer/IdentityServer4/blob/2.3.0/src/Validation/Default/TokenRequestValidator.cs#L776

Both have two placeholders, `values`, and `details`. But you'll notice there's only one placeholder argument in the logging string, intended to be replaced by `details`. If the callers of `LogError`/`LogWarning` specify an additional placeholder, intended to be replaced by `values`, the log message is formatted as intended. If not, the empty `values` object gets filled in where `details` was intended to be filled in, since "The order of placeholders, not their names, determines which parameters are used to provide their values." (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#log-message-template)

**Comment by MCFHTAGENTS** [comment] 2019-03-28 20:12
Ok so we have 2 issues: the empty request error messages  and the root cause of my invalid token which created the issue in the first place! 
Mark

**Comment by jklawrence** [comment] 2019-03-29 16:06
It looks like the empty details I was seeing in other log messages was fixed in 2.4.0.

I opened a PR to address details not being included in the "refresh token validation failed" message. 

@brockallen @leastprivilege I know you said you were going to have a look, so if you're already addressing this a different way I'm happy to close my PR. Just had a little spare time and thought I'd try to help out.

**Comment by leastprivilege** [comment] 2019-03-30 07:36
We'll have a look

**Comment by brockallen** [comment] 2019-06-30 20:25
PR was merged, so I think I close this issue. Let me know if I'm mistaken.

**Comment by MCFHTAGENTS** [comment] 2019-06-30 20:29
Brock
I think the PR was to do with the missing info in the log. I don’t think it covered the over zealous archiving when token clean up is enabled?
Thanks
Mark

**Comment by brockallen** [comment] 2019-06-30 20:36
Oops, ok then. Reopening.

**Comment by brockallen** [comment] 2019-08-09 14:26
This will be covered here: #3519. Thanks.

**Closed by brockallen** 2019-08-09 14:26 UTC
Labels: feature request
