### ISSUE TITLE
CorsPolicyService did not allow origin: https://example.com

### ISSUE THREAD

**Issue by LindaLawton** [IdentityServer/IdentityServer4#2680] opened 2018-10-04 09:09 UTC
**CorsPolicyService warnings in logs.**

Let me start by saying that i am not exactly clear on what Cors policy does in the identity server.  My assumption is that its limiting where the client application is coming from.  

>CorsPolicyService did not allow origin: https://example.com

I am assuming that the issue is that we have a number of clients who have not set up the Cors correctly for the client within the database.  However that being said our users are not seeing any issues this is just appearing in my logs.   So nothing is stopping them from logging in and I am just getting a warning that they are doing it?

My issue is that there is no way for me to identify out of the logs which client is currently throwing this warning.   We have managed to track down a few of them with some guess work but I am still getting a flood of them in my logs.

**Add client id to the warning message.**

What i would like to see is some identification in the logging in the ProcessAsync method informing us which client is causing this warning.   May i suggest client id?

[CorsPolicyProvider](https://github.com/IdentityServer/IdentityServer4/blob/75b1a660c3cab2580112e6e0288f3f6bed8189f9/src/Hosting/CorsPolicyProvider.cs#L69)

`  _logger.LogWarning("CorsPolicyService did not allow origin: {origin}", origin);`

**Comment by brockallen** [comment] 2018-10-04 12:03
The problem is that the client_id is not something we have on CORS requests, as those are HTTP OPTIONS requests (usually) into the server, separate from the actual request that would follow (if CORS is allowed). Also, the CORS processing happens globally and thus we're not into the routing system so we don't have our endpoint processing code running to do any URL/param parsing.

**Comment by LindaLawton** [comment] 2018-10-04 12:04
Do you have a recommendation as to how to track down the causes of these warnings then?

**Comment by brockallen** [comment] 2018-10-04 12:07
Well the origin itself -- does that not help, or are all of your clients on one origin?

**Comment by LindaLawton** [comment] 2018-10-04 12:19
They are third party developers so its a bit hard how many applications they have created.   A lot of the clients run with the same domain just have different sub domains.

>https://blah-web-develop-dev.domain.io

How would you suggest we guess where that is coming from?

**Comment by LindaLawton** [comment] 2018-10-04 12:27
I dont think i follow you?   Where can i log this?

**Comment by brockallen** [comment] 2018-10-04 12:32
Perhaps wrap our cors policy service with your own to log? Or log all OPTIONS requests? Or add a logging sink that activates on that category and then logs the url?

**Comment by LindaLawton** [comment] 2018-10-04 12:44
You always come up with the most elegant solutions.    I will be back Assuming you want me to post the code here when i get it working.  Otherwise i guess we can just close this since its not possible to log it on your end.

**Comment by brockallen** [comment] 2018-10-04 12:48
I don't care so much about the code, but I am curious why so many log entries. I want to know if the log entries are false/incorrect warnings. I know in Chrome they pass the Origin header for normal POST requests, which looks like a cross-origin call. But I thought we added code to ignore those...

**Comment by LindaLawton** [comment] 2018-10-04 12:50
Its showing up as a warning it looks like its diffidently hitting [L69](https://github.com/IdentityServer/IdentityServer4/blob/75b1a660c3cab2580112e6e0288f3f6bed8189f9/src/Hosting/CorsPolicyProvider.cs#L69).

I would like to say that i could set up an attach process debug for IDs4 but i have not been able to get that to work with my project yet.  Not that i have spent that much time trying.

**Comment by brockallen** [comment] 2018-10-04 15:53
I'll close this for now. If you find out there's a false positive in the logs, reopen please and we can decide what to do.

**Closed by brockallen** 2018-10-04 15:53 UTC
Labels: question

**Comment by LindaLawton** [comment] 2018-10-05 06:20
I guess i am going to have to do some research into what this is exactly before i can decide what a false positive is.   The urls that are popping up are not in the table so i have tried to add them on a few of the clients that have similar redirect uris.

**Comment by topherCarpediem** [comment] 2020-01-03 03:53
The request is coming from jwt.io, if you paste your access token to the token decoder, i think its automatically read the issuer and hit the _https://domain.com/.well-known/openid-configuration_ endpoint to get the configuration and automatically verify its signature. 

PS. I'm not sure if it is jwt.io do this but what i am sure about is jwt.io is making a request to _https://domain.com/.well-known/openid-configuration_ if you paste your access token to its decoder.

See attached photo to see network request when i tried to paste my sample access token.

![image](https://user-images.githubusercontent.com/22724153/71706393-8943b080-2e1f-11ea-8e45-ca7ec795e8d6.png)
