### ISSUE TITLE
Logout null exception /connect/endsession

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer4#201] opened 2016-08-12 09:56 UTC
When I try to logout using the connect/endsession, IdentityServer4 throws a null exception (After a restart). A already logged out response should be returned.

How to reproduce.

User logs in, gets an access_token and saves this to the localstorage (or whatever). Stop the IdentityServer4 and restart.  Try to logout using the connect/endsession with the existing token.

Code: https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow

Request:
```
https://localhost:44345/connect/endsession?id_token_hint=eyJhbGciOiJSUzI1NiIsImtpZCI6IjA2RDNFNDZFOTEwNzNDNUQ0QkMyQzk5ODNCRTlGRjQ0OENGNjQwRDQiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJCdFBrYnBFSFBGMUx3c21ZTy1uX1JJejJRTlEifQ.eyJuYmYiOjE0NzA5OTUwNTEsImV4cCI6MTQ3MDk5NTM1MSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNDUiLCJhdWQiOiJhbmd1bGFyMmNsaWVudCIsIm5vbmNlIjoiTjAuMzcwNjk5NzU4MTE0MTcwMTE0NzA5OTUwMzA5MjgiLCJpYXQiOjE0NzA5OTUwNTEsImF0X2hhc2giOiIyT0hBOE1PUFJzYU9fNVBHTzhmd25RIiwic2lkIjoiOTA4ZDU0ZDRiNWY4ZDI1MjFiM2E5YTFmYzVmNGVlMDYiLCJzdWIiOiI0ODQyMTE1NyIsImF1dGhfdGltZSI6MTQ3MDk5NTA0MywiaWRwIjoiaWRzdnIifQ.VJOEYTkB45obCq2lfkYFRPem2zgaNq9D4cq7WMR3UpdBwp-eAkgRlsA1fmrOqMatrGQvx-bCn9tIAMM1uscp2x3ITAM9eCJV2p-3SThk_TNmcnQjuDDerlImOnJH9JIgdTewLIOkYGwExi7ZBMnHNa16xB7ts07cZ1eYjb3ahIV3pXW9YPPPkyYZ-RMnjPWcaxPXJHC56YAoRIl9YhpiZZtuCxTbWzLne50N6peP94y3V7vuasDFKhlqqgxAGxQNbtov_eGKwGWSTdEuMrtIlxg6lx21SJdAi9l6Q1xJAP7vJl4R4gegWuESVLzoj3juwcDeCEi_Uphyh0cfWcs_3Q&post_logout_redirect_uri=https://localhost:44311/Unauthorized.html
```

Exception log
```
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 154.1819ms 200 text/plain
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:44345/connect/endsession?id_token_hint=eyJhbGciOiJSUzI1NiIsImtpZCI6IjA2RDNFNDZFOTEwNzNDNUQ0QkMyQzk5ODNCRTlGRjQ0OENGNjQwRDQiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJCdFBrYnBFSFBGMUx3c21ZTy1uX1JJejJRTlEifQ.eyJuYmYiOjE0NzA5OTUwNTEsImV4cCI6MTQ3MDk5NTM1MSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNDUiLCJhdWQiOiJhbmd1bGFyMmNsaWVudCIsIm5vbmNlIjoiTjAuMzcwNjk5NzU4MTE0MTcwMTE0NzA5OTUwMzA5MjgiLCJpYXQiOjE0NzA5OTUwNTEsImF0X2hhc2giOiIyT0hBOE1PUFJzYU9fNVBHTzhmd25RIiwic2lkIjoiOTA4ZDU0ZDRiNWY4ZDI1MjFiM2E5YTFmYzVmNGVlMDYiLCJzdWIiOiI0ODQyMTE1NyIsImF1dGhfdGltZSI6MTQ3MDk5NTA0MywiaWRwIjoiaWRzdnIifQ.VJOEYTkB45obCq2lfkYFRPem2zgaNq9D4cq7WMR3UpdBwp-eAkgRlsA1fmrOqMatrGQvx-bCn9tIAMM1uscp2x3ITAM9eCJV2p-3SThk_TNmcnQjuDDerlImOnJH9JIgdTewLIOkYGwExi7ZBMnHNa16xB7ts07cZ1eYjb3ahIV3pXW9YPPPkyYZ-RMnjPWcaxPXJHC56YAoRIl9YhpiZZtuCxTbWzLne50N6peP94y3V7vuasDFKhlqqgxAGxQNbtov_eGKwGWSTdEuMrtIlxg6lx21SJdAi9l6Q1xJAP7vJl4R4gegWuESVLzoj3juwcDeCEi_Uphyh0cfWcs_3Q&post_logout_redirect_uri=https://localhost:44311/Unauthorized.html  
IdentityServer4.Endpoints.EndSessionEndpoint:Information: Processing singout request
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Users\damien.bowden\.nuget\packages\System.IdentityModel.Tokens.Jwt\5.0.0\lib\netstandard1.4\System.IdentityModel.Tokens.Jwt.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.Security.Cryptography.Encoding.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.Security.Cryptography.Csp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.Security.Cryptography.Cng.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Users\damien.bowden\.nuget\packages\IdentityModel\2.0.0-beta5\lib\netstandard1.3\IdentityModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
IdentityServer4.Validation.TokenValidator:Information: Token validation success
{
  "ClientId": "angular2client",
  "ClientName": "angular2client",
  "ValidateLifetime": false,
  "Claims": {
    "nbf": 1470995051,
    "exp": 1470995351,
    "iss": "https://localhost:44345",
    "aud": "angular2client",
    "nonce": "N0.37069975811417011470995030928",
    "iat": 1470995051,
    "at_hash": "2OHA8MOPRsaO_5PGO8fwnQ",
    "sid": "908d54d4b5f8d2521b3a9a1fc5f4ee06",
    "sub": "48421157",
    "auth_time": 1470995043,
    "idp": "idsvr"
  }
}
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.IO.MemoryMappedFiles.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.IO.UnmanagedMemoryStream.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
IdentityServer4.Hosting.IdentityServerMiddleware:Critical: Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at IdentityServer4.Validation.EndSessionRequestValidator.<ValidateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Endpoints.EndSessionEndpoint.<ProcessSignoutAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Endpoints.EndSessionEndpoint.<ProcessAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Error: An unhandled exception has occurred while executing the request

System.NullReferenceException: Object reference not set to an instance of an object.
   at IdentityServer4.Validation.EndSessionRequestValidator.<ValidateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Endpoints.EndSessionEndpoint.<ProcessSignoutAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Endpoints.EndSessionEndpoint.<ProcessAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()
```

**Comment by brockallen** [comment] 2016-08-18 20:47
I can't reproduce this with my local setup. Any more info that might help?

**Comment by brockallen** [comment] 2016-08-18 20:54
From inspecting the code I might have tracked it down. I'll see if I can write a test to repro.

**Comment by brockallen** [comment] 2016-08-18 21:09
@leastprivilege for this situation, what should we do? client triggers signout endpoint with valid id_token_hint & post_logout_redirect_uri params, but user is no longer signed into idsvr -- should those params be considered valid or invalid for redirecting back to client?

**Comment by brockallen** [comment] 2016-08-18 21:36
BTW, the NRE is now fixed. Just need to know what behavior is desired to close this issue.

**Comment by brockallen** [comment] 2016-08-26 17:30
Closing now since bug is fixed, and we will honor end session params even if user is signed out at IdSvr.

**Closed by brockallen** 2016-08-26 17:30 UTC
Labels: bug

**Comment by damienbod** [comment] 2016-08-26 17:42
cool, thanks, is it already released in the latest Nuget package, or is it still to be released?

Greetings Damien

**Comment by brockallen** [comment] 2016-08-26 17:45
nothing on NuGet yet, but these fixes are on the myget feed.

**Comment by damienbod** [comment] 2016-08-26 17:45
thanks
