### ISSUE TITLE
HomeController.Login does NOT handle 'cancel'

### ISSUE THREAD

**Issue by gvdonovan** [IdentityServer/IdentityServer4#2556] opened 2018-08-17 21:35 UTC
Based on the latest bits the IdentityServer4.QuickStart.UI does not handle the [Cancel] button.

**Comment by brockallen** [comment] 2018-08-17 22:11
In what way?

**Comment by gvdonovan** [comment] 2018-08-18 00:35
What should be done in mvc client to handle access denied when user cancels
login?

**Comment by brockallen** [comment] 2018-08-18 00:42
That's up to the client application (and the tech stack you use to help with the protocol). In ASP.NET Core MVC, you'd handle the error event.

**Comment by gvdonovan** [comment] 2018-08-18 05:44
I'm using the MVC app (implicit) that is provided in the samples.  Would
like to redirect to an 'Access Denied' page or something of the like if
they hit cancel.  It currently returns to http://localhost:5002/signin-oidc
with the following error:

OpenIdConnectProtocolException: Message contains error: 'access_denied',
error_description: 'error_description is null', error_uri: 'error_uri is
null'.

Is there a way to define an AccessDeniedPath in the client that Identity
Server could check?

Thanks!

**Comment by brockallen** [comment] 2018-08-18 09:00
> It currently returns to http://localhost:5002/signin-oidc with the following error: 
> OpenIdConnectProtocolException: Message contains error: 'access_denied', error_description: 'error_description is null', error_uri: 'error_uri is null'.

This is by design and up to the client to handle. Now if you're asking for the samples to be clarified, then we will gladly accept a PR for that. You'd handle it by handling the error event on OIDC options in the client.

**Comment by brockallen** [comment] 2018-08-18 10:34
Closing. If you wish to beef up the same clients, please send a PR. Thanks.

**Closed by brockallen** 2018-08-18 10:34 UTC
Labels: question

**Comment by blankenbush** [comment] 2018-11-16 21:14
You can try something like this...

```
.AddOpenIdConnect("oidc", options =>
{
    // other options here...

    options.Events = new OpenIdConnectEvents
    {
        OnRemoteFailure = (context) =>
        {
            context.Response.Redirect("/");
            context.HandleResponse();
            
            return Task.CompletedTask;
        }
    };
});

```

**Comment by findmoon** [comment] 2019-06-19 01:06
> You can try something like this...
> 
> ```
> .AddOpenIdConnect("oidc", options =>
> {
>     // other options here...
> 
>     options.Events = new OpenIdConnectEvents
>     {
>         OnRemoteFailure = (context) =>
>         {
>             context.Response.Redirect("/");
>             context.HandleResponse();
>             
>             return Task.CompletedTask;
>         }
>     };
> });
> ```

hi,when I use `OnRemoteFailure` Event,i did solve this bug on response page.but,It still appearing in the console。Is there any way to cancel the error in the console? thank you。感谢能指导下
![image](https://user-images.githubusercontent.com/18387852/59729494-6978e080-9271-11e9-9793-386dea581153.png)

**Comment by gph2000** [comment] 2019-06-22 07:51
I am facing a this situation too. I will be reading this thread carefully to see what I can make of the designed behaviour, However I have already established that if I remove the complex cancel logic in the Identity Server example and replace it with a simple redirect to the home page (or an access denied page) of the calling client then this will work for an MVC only stack. But I want to share my Identity Server with windows forms clients too so hence I need to make the expected behaviour do its thing.
