### ISSUE TITLE
AddDeveloperSigningCredential() issue with ASP.NET Core 2.2 in-process hosting

### ISSUE THREAD

**Issue by webbywebdesign** [IdentityServer/IdentityServer4#3034] opened 2019-02-14 22:36 UTC
Your sample code in document:
.AddDeveloperSigningCredential()
Is not working on .Net Core 2.2 as GetCurrentDirectory will return the IIS process folder location VS the base folder of the App.

### Relevant parts of the log file

```
<log goes here>
```
-- Suggested code??
var filename = Path.Combine(AppContext.BaseDirectory, "tempkey.rsa");
.AddDeveloperSigningCredential(filename: filename)

**Comment by brockallen** [comment] 2019-02-14 22:41
Does `BaseDirectory` work the same on .NET Core as Full .NET?

**Comment by webbywebdesign** [comment] 2019-02-14 23:08
Not sure

**Comment by webbywebdesign** [comment] 2019-02-15 04:09
I believe so based on : https://docs.microsoft.com/en-us/dotnet/api/system.appcontext.basedirectory?view=netframework-4.7.2

**Comment by leastprivilege** [comment] 2019-02-15 05:58
Starting with ASP.NET Core 2.2 there is an in-process hosting option for IIS. If this is used (which seems to be the default in the new templates) the working directory changes to the IIS directory.

Will give the AppContext a try.

**Comment by leastprivilege** [comment] 2019-02-15 06:12
`AppContext.BasePath` is unfortunately not quite the same. It points to `/bin/debug` as opposed to the content root.

Needs more investigation. You can always pass in an explicit file name to `AddDeveloperSigningCredential`.

**Comment by leastprivilege** [comment] 2019-02-15 06:52
According to David Fowler this has been fixed in 2.2

https://twitter.com/davidfowl/status/1096296090670837760

**Comment by leastprivilege** [comment] 2019-02-15 07:12
Confirmed that it works as expected on 2.2.2

**Closed by leastprivilege** 2019-02-15 07:12 UTC
Labels: bug report
