### ISSUE TITLE
Violation of PRIMARY KEY constraint 'PK_PersistedGrants'

### ISSUE THREAD

**Issue by jwcao** [IdentityServer/IdentityServer4#3292] opened 2019-05-24 13:18 UTC
### Issue / Steps to reproduce the problem
We are seeing in our production exception logging messages about a violation of the primary key constraint PK_PersistedGrants. We have never seen this in development, so I do not know specific steps to reproduce or the impact of the error. It only happens a few times a day from thousands of requests, so it is rare, but I wanted to get the community's thoughts on it.

Thanks

### Relevant parts of the log file

```
Unhandled exception: An error occurred while updating the entries. See the inner exception for details.Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Violation of PRIMARY KEY constraint 'PK_PersistedGrants'. Cannot insert duplicate key in object 'dbo.PersistedGrants'. The duplicate key value is (---removed---).The statement has been terminated.   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()   at System.Data.SqlClient.SqlDataReader.get_MetaData()   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)   --- End of inner exception stack trace ---   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)   at IdentityServer4.EntityFramework.Stores.PersistedGrantStore.StoreAsync(PersistedGrant token)   at IdentityServer4.Stores.DefaultGrantStore`1.StoreItemAsync(String key, T item, String clientId, String subjectId, DateTime created, Nullable`1 expiration)   at IdentityServer4.Services.DefaultRefreshTokenService.UpdateRefreshTokenAsync(String handle, RefreshToken refreshToken, Client client)   at IdentityServer4.ResponseHandling.TokenResponseGenerator.ProcessRefreshTokenRequestAsync(TokenRequestValidationResult request)   at IdentityServer4.ResponseHandling.TokenResponseGenerator.ProcessAsync(TokenRequestValidationResult request)   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
```

**Comment by brockallen** [comment] 2019-05-24 14:36
What database are you using?

**Comment by jwcao** [comment] 2019-05-24 15:03
It's an MS SQL database.

**Comment by LindaLawton** [comment] 2019-05-27 08:33
@jwcao   Which version of Ids are you using?  

What does the index look like in production?  Hers mine.

```
/****** Object:  Index [PK_PersistedGrants]    Script Date: 5/27/2019 10:31:57 AM ******/
ALTER TABLE [dbo].[PersistedGrants] ADD  CONSTRAINT [PK_PersistedGrants] PRIMARY KEY CLUSTERED 
(
	[Key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
```

@brockallen if it helps i am running the latest and greatest IDs.    MS SQL server with entity framework.  I checked my logs for the last month I am not seeing it in test or production.

**Comment by brockallen** [comment] 2019-05-27 13:09
I have another customer with a similar issue because the DB column is case insensitive, but the value we generate case sensitive (because the encoding)..

**Comment by jwcao** [comment] 2019-06-03 19:17
Our database column was case insensitive, but we updated it to be case sensitive, and we are still experiencing this issue. Specifically it was changed from SQL_Latin1_General_CP1_CI_AS to  SQL_Latin1_General_CP1_CS_AS.

**Comment by brockallen** [comment] 2019-06-30 20:14
Ok, I had a look and the implication of my comment above was incorrect. For some reason I thought we were using base64 encoding for the value, but we're hex encoding (which should not matter for the comparison). On a side note, now it makes me wonder what other customer's case sensitivity issue I was [mis-]remembering.

In any event, I'm not sure what the issue is then. What are the chances that you are re-creating the same 32 byte random number? The underlying value is created from the object returned from `RandomNumberGenerator.Create`, which is documented here: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.randomnumbergenerator.getbytes?view=netframework-4.8#System_Security_Cryptography_RandomNumberGenerator_GetBytes_System_Byte___. 

So the only thing I can think of is perhaps somehow the SQL statement is being issued twice to the DB? Perhaps there's some re-try feature in the SQL connection config?

**Comment by leastprivilege** [comment] 2019-11-24 10:09
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Closed by leastprivilege** 2019-11-24 10:09 UTC
Labels: question
