### ISSUE TITLE
How to solve this issue "Refresh token cannot be found in store"?

### ISSUE THREAD

**Issue by rahulraj001234** [IdentityServer/IdentityServer4#1595] opened 2017-10-06 10:29 UTC
I have an MVC application that is registered with Identityserver. I am maintaining a persisted store (SQL server) to store refresh token information. When my MVC application makes a request for new refreshed tokens I am getting this error "Refresh token cannot be found in store". Most of the time refresh token process works for me but occasionally this issue occurs. I am not able to reproduce this issue.

**Log:**
Identityserver logs
2017-09-20 17:27:43,197 ERROR [3] IdentityServer4.Validation.TokenRequestValidator - Refresh token cannot be found in store: 2fa923752c42bdcafd50fd0aec9935b10cb11718b015a3c738b5760b07d8eb53
2017-09-20 17:27:43,197 ERROR [3] IdentityServer4.Validation.TokenRequestValidator - {
  "ClientId": "MVC",
  "ClientName": "MVC Client",
  "GrantType": "refresh_token",
  "RefreshToken": "2fa923752c42bdcafd50fd0aec9935b10cb11718b015a3c738b5760b07d8eb53",
  "Raw": {
    "grant_type": "refresh_token",
    "refresh_token": "2fa923752c42bdcafd50fd0aec9935b10cb11718b015a3c738b5760b07d8eb53"
  }
}

**Comment by brockallen** [comment] 2017-10-06 12:12
Not enough info.

**Comment by rahulraj001234** [comment] 2017-10-09 05:29
For my MVC web application  I am following hybrid flow. I have configured access token absolute expiry as 30 minutes. On access token expiry 28th minute I am making a refresh token request to Identityserver to get new tokens by passing refresh token code.
 
I'm using the below code to achieve the result. 
refreshtoken="2fa923752c42bdcafd50fd0aec9935b10cb11718b015a3c738b5760b07d8eb53"
 TokenReponse tokenResponse = await tokenClient.RequestRefreshTokenAsync(refreshToken);

Occasionally the above refresh token process fails. The tokenResponse result would be "InvalidGrant".  
Below error information is logged in the IdentityServer logs

Identityserver logs
2017-09-20 17:27:43,197 ERROR [3] IdentityServer4.Validation.TokenRequestValidator - **Refresh token cannot be found in store**: 2fa923752c42bdcafd50fd0aec9935b10cb11718b015a3c738b5760b07d8eb53
2017-09-20 17:27:43,197 ERROR [3] IdentityServer4.Validation.TokenRequestValidator - {
"ClientId": "MVC",
"ClientName": "MVC Client",
"GrantType": "refresh_token",
"RefreshToken": "2fa923752c42bdcafd50fd0aec9935b10cb11718b015a3c738b5760b07d8eb53",
"Raw": {
"grant_type": "refresh_token",
"refresh_token": "2fa923752c42bdcafd50fd0aec9935b10cb11718b015a3c738b5760b07d8eb53"
}
}

As this error occurs occasionally I am not able to reproduce it and also I'm unable to find a pattern. On how to reproduce this issue.

Below is the access token and Refresh token configuration 
I'm Using Identityserver 4
AbsoluteRefreshTokenLifetime=30 days
SlidingRefreshTokenLifetime = 15days
AccessTokenExpiry=30 minutes

**Comment by brockallen** [comment] 2017-10-09 14:11
And you've configured for deployment? http://docs.identityserver.io/en/release/topics/deployment.html#identityserver-operational-data

**Comment by rahulraj001234** [comment] 2017-10-10 06:52
Yes I have configured for deployment

**Comment by rahulraj001234** [comment] 2017-10-10 06:55
I am storing all the IdentityServer operational data, IdentityServer configuration data in tables

**Comment by leastprivilege** [comment] 2017-10-31 09:52
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Closed by leastprivilege** 2017-10-31 09:52 UTC
Labels: question

**Comment by diogoxpandit** [comment] 2018-10-22 14:03
Anyone else had the same problem? With the same refresh token, sometimes the Identity server returns the refresh token and sometimes don't.

**Comment by Jehoel** [comment] 2019-02-04 07:00
I'm having the same issue - where sometimes it complains that a refresh token wasn't found in the store.

I enabled extra logging in my entire system and I found out that some IdentityServer client website visitors are reusing old `refresh_token` values - when the token is reused a second time it fails. I'm trying to figure out why they aren't dropping the old value.

I suspect that the problem is my ASP.NET Core MVC application is setting a new replacement cookie that's too big (as I currently have a lot of Claims), so the browsers ignore the `Set-Cookie` header and keep-on using the old cookie value.

**Comment by zinov** [comment] 2019-04-10 15:14
@leastprivilege, @brockallen is not there a mechanism on IdentityServer to drop old values of refresh_token once they expire?
On my Asp.NET Core MVC client I am using an old refresh_token for the second time and I am getting an exception of Invalid_Grants, and when I am checking the logs of IdentityServer, the only information I am getting is this:

> IdentityServer4.Validation.TokenValidator:Warning: Invalid refresh token
IdentityServer4.Validation.TokenValidator:Warning: Invalid refresh token
IdentityServer4.Validation.TokenRequestValidator:Warning: Refresh token validation failed. aborting., request details:
IdentityServer4.Validation.TokenRequestValidator:Warning: Refresh token validation failed. aborting., request details:
