### ISSUE TITLE
Strange Behavior in SecretValidator "HashedSharedSecretValidator"

### ISSUE THREAD

**Issue by stefanlohr** [IdentityServer/IdentityServer4#2085] opened 2018-02-19 16:30 UTC
we upgraded from IdentityServer 1.52 to 2.1.2 and after the update most of your users (all with sharedsecret) cant get a bearer token anymore.

we have a client naming schema which is more or less like "<type><.name>" like interface.company_a or postman.<name>

i can create new secrets with an old client and it will not work - also renaming will not work. i can create new clients following our name schema and it will not work. 

i can create a new client without the "." and assign a new shared secret and it will work. funny if i rename the new created client and add a "." in the middle it still works.

we create all our sharedsecrets on our side (hashed uuid).

```
2018-02-19 17:07:36.296 +01:00 [Debug] Request path "/connect/token" matched to endpoint type "Token"
2018-02-19 17:07:36.297 +01:00 [Debug] Endpoint enabled: "Token", successfully created handler: "IdentityServer4.Endpoints.TokenEndpoint"
2018-02-19 17:07:36.297 +01:00 [Information] Invoking IdentityServer endpoint: "IdentityServer4.Endpoints.TokenEndpoint" for "/connect/token"
2018-02-19 17:07:36.297 +01:00 [Debug] Start token request.
2018-02-19 17:07:36.297 +01:00 [Debug] Start client validation
2018-02-19 17:07:36.297 +01:00 [Debug] Start parsing Basic Authentication secret
2018-02-19 17:07:36.297 +01:00 [Debug] Parser found secret: "BasicAuthenticationSecretParser"
2018-02-19 17:07:36.297 +01:00 [Debug] Secret id found: "Postman.Stefan"
2018-02-19 17:07:36.307 +01:00 [Debug] "Postman.Stefan" found in database: True
2018-02-19 17:07:36.307 +01:00 [Debug] No matching hashed secret found.
2018-02-19 17:07:36.310 +01:00 [Debug] Secret validators could not validate secret
2018-02-19 17:07:36.311 +01:00 [Error] Client secret validation failed for client: "Postman.Stefan".
2018-02-19 17:07:39.682 +01:00 [Information] Clearing 0 tokens
2018-02-19 17:08:09.685 +01:00 [Information] Clearing 0 tokens
2018-02-19 17:08:39.700 +01:00 [Information] Clearing 0 tokens
2018-02-19 17:08:43.077 +01:00 [Debug] Request path "/connect/token" matched to endpoint type "Token"
2018-02-19 17:08:43.077 +01:00 [Debug] Endpoint enabled: "Token", successfully created handler: "IdentityServer4.Endpoints.TokenEndpoint"
2018-02-19 17:08:43.077 +01:00 [Information] Invoking IdentityServer endpoint: "IdentityServer4.Endpoints.TokenEndpoint" for "/connect/token"
2018-02-19 17:08:43.077 +01:00 [Debug] Start token request.
2018-02-19 17:08:43.077 +01:00 [Debug] Start client validation
2018-02-19 17:08:43.077 +01:00 [Debug] Start parsing Basic Authentication secret
2018-02-19 17:08:43.077 +01:00 [Debug] Parser found secret: "BasicAuthenticationSecretParser"
2018-02-19 17:08:43.077 +01:00 [Debug] Secret id found: "Postman-dings"
2018-02-19 17:08:43.087 +01:00 [Debug] "Postman-dings" found in database: True
2018-02-19 17:08:43.087 +01:00 [Debug] Secret validator success: "HashedSharedSecretValidator"
2018-02-19 17:08:43.087 +01:00 [Debug] Client validation success
2018-02-19 17:08:43.087 +01:00 [Debug] Start token request validation
2018-02-19 17:08:43.087 +01:00 [Debug] Start client credentials token request validation
2018-02-19 17:08:43.088 +01:00 [Debug] Found [] identity scopes in database
2018-02-19 17:08:43.093 +01:00 [Debug] Found ["Caremore.Assets", "Caremore.DataHub.REST"] API scopes in database
2018-02-19 17:08:43.094 +01:00 [Debug] Found [] identity scopes in database
2018-02-19 17:08:43.098 +01:00 [Debug] Found ["Caremore.Assets", "Caremore.DataHub.REST"] API scopes in database
2018-02-19 17:08:43.098 +01:00 [Debug] "Postman-dings" credentials token request validation success
2018-02-19 17:08:43.098 +01:00 [Information] Token request validation success
"{
  \"ClientId\": \"Postman-dings\",
  \"ClientName\": \"Postman-dings\",
  \"GrantType\": \"client_credentials\",
  \"Scopes\": \"Caremore.Assets Caremore.DataHub.REST\",
  \"Raw\": {
    \"grant_type\": \"client_credentials\",
    \"scope\": \"\",
    \"client_id\": \"Postman-dings\"
  }
}"
2018-02-19 17:08:43.098 +01:00 [Debug] Getting claims for access token for client: "Postman-dings"
2018-02-19 17:08:43.103 +01:00 [Debug] Token request success.
2018-02-19 17:08:53.008 +01:00 [Debug] Request path "/connect/token" matched to endpoint type "Token"
2018-02-19 17:08:53.008 +01:00 [Debug] Endpoint enabled: "Token", successfully created handler: "IdentityServer4.Endpoints.TokenEndpoint"
2018-02-19 17:08:53.008 +01:00 [Information] Invoking IdentityServer endpoint: "IdentityServer4.Endpoints.TokenEndpoint" for "/connect/token"
2018-02-19 17:08:53.008 +01:00 [Debug] Start token request.
2018-02-19 17:08:53.008 +01:00 [Debug] Start client validation
2018-02-19 17:08:53.008 +01:00 [Debug] Start parsing Basic Authentication secret
2018-02-19 17:08:53.008 +01:00 [Debug] Parser found secret: "BasicAuthenticationSecretParser"
2018-02-19 17:08:53.009 +01:00 [Debug] Secret id found: "Hans"
2018-02-19 17:08:53.025 +01:00 [Debug] "Hans" found in database: True
2018-02-19 17:08:53.025 +01:00 [Debug] Secret validator success: "HashedSharedSecretValidator"
2018-02-19 17:08:53.025 +01:00 [Debug] Client validation success
2018-02-19 17:08:53.025 +01:00 [Debug] Start token request validation
2018-02-19 17:08:53.025 +01:00 [Debug] Start client credentials token request validation
2018-02-19 17:08:53.027 +01:00 [Debug] Found [] identity scopes in database
2018-02-19 17:08:53.031 +01:00 [Debug] Found ["Caremore.Assets", "Caremore.DataHub.REST"] API scopes in database
2018-02-19 17:08:53.033 +01:00 [Debug] Found [] identity scopes in database
2018-02-19 17:08:53.037 +01:00 [Debug] Found ["Caremore.Assets", "Caremore.DataHub.REST"] API scopes in database
2018-02-19 17:08:53.037 +01:00 [Debug] "Hans" credentials token request validation success
2018-02-19 17:08:53.037 +01:00 [Information] Token request validation success
"{
  \"ClientId\": \"Hans\",
  \"ClientName\": \"Hans\",
  \"GrantType\": \"client_credentials\",
  \"Scopes\": \"Caremore.Assets Caremore.DataHub.REST\",
  \"Raw\": {
    \"grant_type\": \"client_credentials\",
    \"scope\": \"\",
    \"client_id\": \"Hans\"
  }
}"
2018-02-19 17:08:53.037 +01:00 [Debug] Getting claims for access token for client: "Hans"
2018-02-19 17:08:53.041 +01:00 [Debug] Token request success.
```

**Comment by leastprivilege** [comment] 2018-02-20 08:09
We recently fixed a bug with how credentials transmitted via the authorization header are decoded (https://tools.ietf.org/html/rfc6749#section-2.3.1).

My guess is you are also encoding them not 100% correctly. See this discussion:

https://github.com/IdentityServer/IdentityServer4/issues/2039

**Comment by stefanlohr** [comment] 2018-02-20 08:35
i use postman to test our api and to get the bearer tokens. 

![2018-02-20 09_33_17-postman](https://user-images.githubusercontent.com/5890459/36414072-3855f9e8-1621-11e8-85ea-2d2ec95a3b49.png)

i tried this manual with the credtials like described in the mentioned post
`Authorization Basic Base64(FormUrlEncode(client_id):FormUrlEncode(client_secret)`
i still got bad request.

**Comment by leastprivilege** [comment] 2018-02-20 09:04
Hm - then this needs some debugging.

**Comment by stefanlohr** [comment] 2018-02-20 11:31
what can i do to debug this?

**Comment by leastprivilege** [comment] 2018-02-20 12:19
Download the repo, set up a client and put a breakpoint into the secret validator.

As an alternative you can also send the id/secret in the POST body.

**Comment by stefanlohr** [comment] 2018-02-20 13:00
after sending the id / secret in the body it works for all clients / secrets i have availble for test. i will still debug it because its frustrating for me that all clients have to change their code to authenticate on our api

**Comment by leastprivilege** [comment] 2018-02-26 08:48
What did the debugging bring up?

I published a new version of IdentityModel - there's a new property on TokenClient that let's you choose the encoding style - it defaults to Rfc6749 behavior.

https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/TokenClient.cs#L133

**Comment by stefanlohr** [comment] 2018-02-26 13:10
Hi, im currently on medical leave so i can't debug it right away. hopefully i can do it in a few days again. :-(

**Comment by leastprivilege** [comment] 2018-02-28 07:46
OK - no prob. Gute Besserung!

**Comment by siemens-slohr** [comment] 2018-03-07 20:14
Hi Dominick,

i could reproduce the same behavior we are having right now. 

i cloned the repositroy and used this client to test.
`
                new Client
                {
                    ClientId = "Postman.Stefan",
                    ClientSecrets =
                    {
                        new Secret("BmM4cUNGwD+BKRKzjJhSoDUlUhY0yzQMGn+mIud04Xi3ED1zEDq4w9Xe75U9x3tEl7zwsntGm8QAHJXF5zLGFg==".Sha256())
                    },

                    AllowedGrantTypes = GrantTypes.ClientCredentials,
                    AllowedScopes = { "api1", "api2.read_only" }
                },
`
authentication via header is not possible, authentication via body works fine.

**Comment by leastprivilege** [comment] 2018-03-08 06:32
yeah - you need to debug. Otherwise we'll not find out where the problem really occurs.

**Comment by brockallen** [comment] 2018-03-14 18:12
Any update @stefanlohr?

**Comment by siemens-slohr** [comment] 2018-03-15 15:46
im currently on vacation. will be back in april.

**Comment by chrisowhite** [comment] 2018-04-06 01:42
I've found you have to be careful about which framework encoding/decoding method you use. A plus sign is treated differently between URL encoding and form URL encoding.

https://dotnetfiddle.net/GxckKA

**Comment by siemens-slohr** [comment] 2018-04-06 07:26
I figured out that this results from diffrent characters like the '+'. i dont know why it worked before and not anymore. :-/ therefor i have to debug - will do this end of next week (when im back from vacation).

**Comment by siemens-slohr** [comment] 2018-04-13 17:01
i was unable to discover the origin of this problem.

due to other important issues we face currently - we will stick with a workaround (generate secretes without special characters which will cause this error).

**Comment by brockallen** [comment] 2018-05-11 21:37
> i was unable to discover the origin of this problem.

Closing. If you still have issues, feel free to reopen.

**Closed by brockallen** 2018-05-11 21:37 UTC
Labels: question
