### ISSUE TITLE
How to make single-signout happen when logout is done with JSwebclient using implicit flow?

### ISSUE THREAD

**Issue by pmaheshgupta** [IdentityServer/IdentityServer4#1167] opened 2017-05-15 08:38 UTC
I am having 3 apps registered with Identityserver4
1.MVC web client
2.JS web client
3. API Resource

when I started all the 3 applications and logged in either of the web client app I am able to login in to the other web client app automatically, single-sign-in works.

When I Logout in MVC application , I am able to logout from JS web client automatically, but when I logout from JS web client first single-signout is not happening, still having a valid session in MVC app.
Isn't there **CheckSession** kind of thing for MVC client? 

Below is the configuration done at MVC Client 
```
 app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
            {
                AuthenticationScheme = "oidc",
                SignInScheme = "Cookies",                
                Authority = "http://localhost:5000",
                RequireHttpsMetadata = false,
                ClientId = "mvc",
                ClientSecret="secret",
                ResponseType = "code id_token",
                SaveTokens = true
            });
```

**Comment by brockallen** [comment] 2017-05-25 15:34
We support the front-channel signout spec: https://openid.net/specs/openid-connect-frontchannel-1_0.html

In short, configure the LogoutUri for the MVC client.

**Comment by pmaheshgupta** [comment] 2017-05-26 07:18
we did configure the LogoutUri of the MVC client.

**Comment by brockallen** [comment] 2017-05-26 11:06
> we did configure the LogoutUri of the MVC client.

You will have to debug why it's not working then. Check the spec for how it's supposed to work.

**Comment by pmaheshgupta** [comment] 2017-05-26 12:56
hi brock allen..


where to debug? Spec says we need to delete cookies.
To delete cookies nd logout "Identity server" docs suggests the below approach in [here](http://docs.identityserver.io/en/release/topics/signout.html)

await HttpContext.Authentication.SignOutAsync();

I think its a bug in the Identityserver .

**Comment by brockallen** [comment] 2017-05-26 13:00
> I think its a bug in the Identityserver .

If it's a bug in IdentityServer, then please show me how or where it's not working in our samples.

**Comment by pmaheshgupta** [comment] 2017-05-26 13:49
you can find the issue in the sample quick start demonstrated [here ](https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/7_JavaScriptClient).

**Comment by brockallen** [comment] 2017-05-26 14:00
> you can find the issue in the sample quick start demonstrated here .

Yes, I know where the samples are. I don't yet understand what the problem is. You asked:

>  Isn't there CheckSession kind of thing for MVC client?

And I told you: 

> We support the front-channel signout spec: https://openid.net/specs/openid-connect-frontchannel-1_0.html

This is how the MVC style apps get notified for SLO. The OIDC MW in the MVC app handles the signout call, assuming you've configured the MVC client in IdSvr correctly with the LogoutUri property.

**Comment by pmaheshgupta** [comment] 2017-05-26 14:03
Yes I did configure the LogoutUri property. Are you saying that the mentioned quick start is handling Single - Signout for MVC app also?

**Comment by brockallen** [comment] 2017-05-26 14:11
> Yes I did configure the LogoutUri property

So then this is what you need to debug -- when the logged out page is rendered in IdentityServer, check in your browser for the iframe that makes a request there. If the request being made at all? Is there an error on the request?

**Comment by pmaheshgupta** [comment] 2017-05-29 06:50
may be I am not clear earlier with my question...

**Scenario** :  Logging in using Single Sign on in to 2 web applications (MVC Client & JS Client).

When I logout from JSClient App logout is happening as expected and got redirected to LogoutURI, No issue in here.

**Issue**
After logging out from the JSClientApp, MVC APP is working as if there is no logout happened, to happen logout I need to logout from the MVC app again.

But if I do the logout from the MVC app first, then JSWebClient get logged out immediately due to "CheckSession" implementation I think.

My question is how to notify the MVC app that logout happened , because the tokens are active and I am able to authenticate.

**Comment by brockallen** [comment] 2017-05-29 14:58
> After logging out from the JSClientApp, MVC APP is working as if there is no logout happened, to happen logout I need to logout from the MVC app again.

This is done with the LogoutUri setting on the client (for the MVC app). On the "logged out" page there should be an iframe to trigger signout at the MVC client. That's what you need to debug to find out why the iframe is not making it to the MVC client for signout. This is explained in the spec I linked above.

**Comment by leastprivilege** [comment] 2017-06-20 15:18
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Closed by leastprivilege** 2017-06-20 15:18 UTC
Labels: question
