### ISSUE TITLE
Revoking token not belonging to a client returns http status 200

### ISSUE THREAD

**Issue by Exocomp** [IdentityServer/IdentityServer4#2252] opened 2018-04-19 20:20 UTC
### Issue / Steps to reproduce the problem

1. Create two clients: client_1 & client_2
2. Create a reference token with client_1
3. Revoke the reference token belonging to client_1 with client_2
4. The identity server logs show the following:

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:5000/connect/revocation application/x-www-form-urlencoded 128
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenRevocationEndpoint for /connect/revocation
warn: IdentityServer4.ResponseHandling.TokenRevocationResponseGenerator[0]
      Client client_2 tried to revoke an access token belonging to a different client: client_1
info: IdentityServer4.Endpoints.TokenRevocationEndpoint[0]
      Token successfully revoked
```

5. Note the log indicates a warning but then indicates the token was successfully revoked ?
6. The client gets a 200 OK as a response ?
7. The token is not really revoked which is what I expect since the client id was wrong

**Comment by LindaLawton** [comment] 2018-05-23 13:23
[TokenRevocationResponseGenerator.cs#L115](https://github.com/IdentityServer/IdentityServer4/blob/b5342381935600af3e06fe8d3d5c48963d6659e2/src/IdentityServer4/ResponseHandling/TokenRevocationResponseGenerator.cs#L115)    Bug it logs a warning but returns true.

@leastprivilege are you on this?

**Comment by brockallen** [comment] 2018-08-03 01:42
IIRC the spec says to return 200 no matter what.

**Comment by leastprivilege** [comment] 2018-08-08 06:37
@LindaLawton does your investigation involve reading specs before declaring bugs?

https://tools.ietf.org/html/rfc7009#section-2.2

closed as by design.

**Comment by Exocomp** [comment] 2018-08-08 20:32
I suggest logging a different message than "Token successfully revoked". Looking at the log it gives the wrong impression that the token has really be successfully revoked.

Perhaps in the log indicate the token was not revoked due to the wrong client or invalid token, since the log is there for troubleshooting purposes that will be helpful.

**Comment by leastprivilege** [comment] 2018-08-09 06:37
There is a warning 

https://github.com/IdentityServer/IdentityServer4/blob/b5342381935600af3e06fe8d3d5c48963d6659e2/src/IdentityServer4/ResponseHandling/TokenRevocationResponseGenerator.cs#L115

Do you want anything beyond that? Want to PR?

**Comment by brockallen** [comment] 2018-11-11 14:46
Any update on a PR for this?

**Closed** 2020-01-17 11:12 UTC
Labels: investigating, wontfix
