### ISSUE TITLE
how can i add extra claim to the user after certain requests?

### ISSUE THREAD

**Issue by A-Mostafa** [IdentityServer/IdentityServer4#3822] opened 2019-11-14 17:46 UTC
I have an application that i need to update the user claims after calling a certain login request ex 

when a user hit the first method he will be logged in with a claim "HasRoleA": true
and when he hit the second method i have to validate he already have the claim HasRoleA: true
and if yes i will add him a different claim "HasRoleB": true

so i can strict some actions that the user had to request both login requests and other action the user had the first claim only keeping in mind that he should pass the two requests to have the two claims

how can i implement those methods, and how to update the userClaims, and how to update the bearertoken?

**Comment by leastprivilege** [comment] 2019-11-22 08:47
This sounds like an application concern. Not a bug report/feature request.

**Comment by leastprivilege** [comment] 2019-11-24 10:11
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Closed by leastprivilege** 2019-11-24 10:11 UTC
Labels: question
