### ISSUE TITLE
expiretimespan is not working

### ISSUE THREAD

**Issue by mrqinxw** [IdentityServer/IdentityServer4#2588] opened 2018-09-04 10:32 UTC
i have set ExpireTimeSpan = TimeSpan.FromMinutes(1), and SlidingExpiration = false,but it's not working,i gets logged out after 1 hour

**Comment by mrqinxw** [comment] 2018-09-05 07:10
@brockallen i want to let user log off after 1 minute,so i did this,
![image](https://user-images.githubusercontent.com/12837565/45076625-729f2380-b11d-11e8-8907-f67580520612.png)
![image](https://user-images.githubusercontent.com/12837565/45076678-98c4c380-b11d-11e8-9006-b806be98a7a5.png)
but,i loged off until 1 hour later, if any else work i have todo?

**Comment by brockallen** [comment] 2018-09-05 12:27
That will allow your cookie middleware control the cookie lifetime yes, rather than the id_token.

**Comment by mrqinxw** [comment] 2018-09-06 02:01
@brockallen 
but the cookie lifetime is not the value what i set
![image](https://user-images.githubusercontent.com/12837565/45130566-bea0a580-b1bb-11e8-9e9a-59098d21f509.png)

**Comment by brockallen** [comment] 2018-09-06 02:34
It seems you have many many questions that are beyond IdentityServer. Since they are not a bug report or an issue, I'm closing this issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Closed by brockallen** 2018-09-06 02:34 UTC
Labels: question
